[default]
DEBUG = true

[mysql]
MYSQL_PASSWORD = "root1234"
MYSQL_HOST = "localhost"
MYSQL_PORT = 3306
MYSQL_DATABASE = "senior_project"

[redis]
REDIS_PORT = 6379
[mail]
MAIL_SERVER = "smtp.gmail.com"
MAIL_PORT = 587
MAIL_USE_TLS = true
MAIL_USERNAME = "your_email@gmail.com"
MAIL_PASSWORD = "your_email_password"