[default]
debug = true
SECRET_KEY = "my_key_project"
[mysql]
#MYSQL_PASSWORD = "root1234"
#MYSQL_HOST = "localhost"
#MYSQL_PORT = 33306
#MYSQL_DATABASE = "senior_project"
MYSQL_PASSWORD = "12345678"
MYSQL_HOST = "localhost"
MYSQL_PORT = 3306
MYSQL_DATABASE = "url_shortener"

[redis]
REDIS_PORT = 6379
[mail]
MAIL_SERVER = "smtp.gmail.com"
MAIL_PORT = 587
MAIL_USE_TLS = true
MAIL_USE_SSL = false
MAIL_USERNAME = "khoatm20@gmail.com"
MAIL_PASSWORD = "zylp qqql oynu rylk"