version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=senior_project
      - MYSQL_PASSWORD=root1234
    ports:
      - "33306:3306"
    volumes:
      - ./data/mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - local-network
  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis_data:/data
    restart: unless-stopped
    networks:
      - local-network
networks:
  local-network:
    driver: bridge